<a href="https://colab.research.google.com/github/coder20910/Chandan/blob/master/Numpy%20Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

In [1]:
import numpy as np

In [3]:
arr = np.array([2,3,4,5])

In [4]:
arr

array([2, 3, 4, 5])

In [5]:
newarr = np.array([[12,32,443]])

In [6]:
newarr.shape

(1, 3)

In [7]:
newarr.dtype

dtype('int64')

In [14]:
newarr[0,2] = 5

# Array Conversion from other Python Structures

In [16]:
listarray = np.array([[2,3,4],[23,32,23],[12,34,22]])

In [17]:
listarray

array([[ 2,  3,  4],
       [23, 32, 23],
       [12, 34, 22]])

In [18]:
listarray.dtype

dtype('int64')

In [19]:
listarray.shape

(3, 3)

In [20]:
listarray.size

9

In [22]:
zeros = np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng = np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace = np.linspace(1,5,12)

In [28]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
emp = np.empty((4,6)) # It gives random elements 4 x 6

In [30]:
emp

array([[1.93333500e-316, 2.10077583e-312, 2.22809558e-312,
        8.48798317e-313, 9.33678149e-313, 2.05833592e-312],
       [2.31297541e-312, 2.33419537e-312, 6.79038653e-313,
        2.01589600e-312, 2.05833592e-312, 9.33678149e-313],
       [2.35541533e-312, 2.46151512e-312, 1.65515672e-312,
        2.33419537e-312, 9.33678149e-313, 8.91238232e-313],
       [2.27053550e-312, 2.05833592e-312, 2.18565567e-312,
        8.70018275e-313, 8.70018274e-313, 0.00000000e+000]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [34]:
ide = np.identity(4) # It creates a n x n identity matrix

In [35]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
arr_r = np.arange(99)

In [37]:
arr_r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr = arr_r.reshape(3,33) # Size of matrix should be syncronized with reshape sizes

In [41]:
arr_r.ravel() # this func converts matrix to a 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Concept of axis

In [42]:
ar = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [44]:
ar.sum(axis = 0) # It will return the  row wise sum of matrix

array([ 8, 11, 14])

In [45]:
ar.sum(axis = 1) # It will return the column wise sum of matrix.

array([ 6, 12, 15])

# *Transpose of a matrix*

In [47]:
ar.T  # Row will be changed into columns and vice-versa.

array([[1, 3, 4],
       [2, 4, 5],
       [3, 5, 6]])

# Some imp attributes

In [48]:
ar.flat # It is used to make 1-d iterator over the array.

In [49]:
ar.ndim # This attribute return the number of dimenson of matrix

2

In [50]:
ar.size # It will return total number of elements in the array

9

In [51]:
ar.nbytes # Total space consumed by array

72

# Arg Methods

In [52]:
one = np.array([1,2,4,3,433,3])

In [54]:
one.argmax()  # It will return the index of max element in the array

4

In [53]:
one.argmin()   # It will return the index of min element in the array

0

In [55]:
one.argsort()   # It will return the index of  element in the increasiing manner of the array

array([0, 1, 3, 5, 2, 4])

In [56]:
ar.argmin() # In multi dimesional array it will first flat the array
            #   and then return index of minimum number according to the 1-d array

0

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [58]:
ar.argsort(axis=0) # returns the index according to the row wise index

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

# Matrix operations

In [60]:
ar1 = np.array([[1,2,3],[2,3,4],
                [4,5,6]])

In [61]:
ar2 = np.array([[1,2,3],[2,3,4],
                [4,5,6]])

In [62]:
ar1 + ar2 # Returns the addition of two matrixes

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 8, 10, 12]])

In [63]:
ar1 * ar2 # Returns the multiplication of two matrixes

array([[ 1,  4,  9],
       [ 4,  9, 16],
       [16, 25, 36]])

# Some imp functions 

In [64]:
ar.sum() # Sum of whole array

33

In [65]:
ar.min() # Returns minimum element from the array

1

In [66]:
ar.max()

6

In [67]:
np.where(ar>3) # Returns tuple of arr where conditions match

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [68]:
np.count_nonzero(ar) # Returns count of non-zero elements

9

In [69]:
np.nonzero(ar) # Returns indices in the various dimensions of non-zero elements

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

# Size comparison b/w list and numpy array

In [71]:
import sys

In [70]:
py_ar = [0,45,3,3]

In [72]:
np_ar = np.array(py_ar)

In [73]:
sys.getsizeof(1)*len(py_ar)     # Size consumed by list

112

In [75]:
np_ar.itemsize * np_ar.size       #Size consumed by numpy array

32

# Numpy array to list

In [76]:
np_ar.tolist()

[0, 45, 3, 3]